#!/usr/bin/env bash
# redirecting to another page

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > sudo /var/www/html/index.html
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-enabled/redirect_me

sudo service nginx start
