#!/usr/bin/env bash
#A script that pings an IP address passed as an argument.
# Check if an IP address is provided as an argument
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Extract the IP address from the argument
ip_address="$1"

# Perform ping operation 5 times
ping -c 5 "$ip_address"

