#!/usr/bin/env bash
# Find the PID of the 4-to_infinity_and_beyond process
process_pid=$(pgrep -fo "4-to_infinity_and_beyond")

if [ -n "$process_pid" ]; then
  echo "Stopping process with PID $process_pid"
  # Send a termination signal to the process
  kill -15 "$process_pid"
else
  echo "Process not found"
fi

