#!/usr/bin/env bash
# Function to handle SIGTERM signal
terminate() {
  echo "I am invincible!!!"
  exit 0
}

# Trap SIGTERM signal and call the terminate function
trap terminate SIGTERM

# Infinite loop with a sleep of 2 seconds between each iteration
while true; do
  echo "To infinity and beyond"
  sleep 2
done
