#!/usr/bin/env bash
# Find the PID of the 7-highlander process
process_pid=$(pgrep -fo "7-highlander")

if [ -n "$process_pid" ]; then
  echo "Killing process with PID $process_pid"
  # Send a termination signal to the process
  kill -15 "$process_pid"
else
  echo "Process not found"
fi

