#!/usr/bin/env bash
#A script that configures an Ubuntu server with the below requirements.

# Backup the original /etc/hosts file
cp /etc/hosts ~/hosts.new

# Update localhost to resolve to 127.0.0.2
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new

# Add entry for facebook.com to resolve to 8.8.8.8
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
cp -f ~/hosts.new /etc/hosts

