#!/usr/bin/env bash
# Connect to the server using the private key ~/.ssh/school
ssh ubuntu@35.153.67.14 -i ~/.ssh/school
# Commands to be executed on the server
exit
EOF

echo "Connection to 35.153.67.14  closed."
